# Install pre-commit hook
#   pre-commit install
# Apply to all files without committing:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: local
    hooks:
      - id: system
        name: black
        entry: poetry run black .
        pass_filenames: false
        language: system
        types: [python]
      - id: system
        name: isort
        entry: poetry run isort .
        pass_filenames: false
        language: system
        types: [python]
      - id: system
        name: pytest
        entry: poetry run pytest --cov --cov-fail-under=100
        pass_filenames: false
        language: system
        types: [python]
      - id: system
        name: flake8
        entry: poetry run flake8 .
        pass_filenames: false
        language: system
        types: [python]
        require_serial: true
        args: [--darglint-ignore-regex, .*] # Skip docstring checks
      - id: system
        name: mypy
        entry: poetry run mypy censys
        pass_filenames: false
        language: system
        types: [python]
        require_serial: true
      - id: system
        name: update autocomplete
        entry: bash scripts/update_autocomplete.sh
        pass_filenames: false
        language: system
        types: []
