# Install pre-commit hook
#   pre-commit install
# Apply to all files without committing:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: system
        name: ruff
        entry: uv run ruff check . --fix
        pass_filenames: false
        language: system
        types: [python]
        require_serial: true
      - id: system
        name: ruff-format
        entry: uv run ruff format .
        pass_filenames: false
        language: system
        types: [python]
      - id: system
        name: pytest
        entry: uv run pytest --cov --cov-fail-under=100
        pass_filenames: false
        language: system
        types: [python]
      - id: system
        name: mypy
        entry: uv run mypy censys
        pass_filenames: false
        language: system
        types: [python]
        require_serial: true
