name: Upload Python Package

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  deploy:
    strategy:
      matrix:
        os: [windows-latest]
        python: ["3.x"]
        poetry: ["1.5.1"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          cache: "poetry"

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip poetry==${{ matrix.poetry }}
          poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: |
          poetry install

      - name: Build and publish
        run: |
          poetry build -n
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
